#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon May 22 17:29:29 2017

@author: frank

题目：用*号输出字母C的图案。 
"""

for i in range(12):
    if i<2 or i>9:
        print '**************'
    elif i==2 or i==9:
        print '****        **'
    else:
        print'****'
        